# $OpenBSD: Makefile,v 1.3.2.1 2010/10/26 07:12:50 stephan Exp $

COMMENT =	node based bulk operations displayed by a view

DISTNAME = 	views_bulk_operations-6.x-1.10
PKGNAME =	drupal6-views_bulk_operations-1.10

MAINTAINER =	Stephan A. Rickauer <stephan@openbsd.org>

RUN_DEPENDS =	::www/drupal6/views

.include <bsd.port.mk>
