# OpenBSD makefile for:	netpipes3.2
# Version required:	4.1.1
# Date created:		17 Nov 1997
# Whom:			ejovi
#
# $Id: Makefile,v 1.1.1.1 1997/11/18 03:28:20 joey Exp $
#

DISTNAME=		netpipes-4.1.1-export
CATEGORIES=		net

MAINTAINER=		marc@OpenBSD.ORG

MASTER_SITES=		ftp://ftp.purplefrog.com/pub/netpipes/

NO_WRKSUBDIR=		yes

.include <bsd.port.mk>
