# $OpenBSD: Makefile,v 1.14.2.1 2000/09/15 04:47:28 marc Exp $

DISTNAME=	Convert-UU-0.40
PKGNAME=	Convert-UU-0.40
CATEGORIES=	converters perl5
NEED_VERSION=	1.295

MAINTAINER=	angelos@openbsd.org

PERMIT_PACKAGE_CDROM=	"no license"
PERMIT_PACKAGE_FTP=	"no license"
PERMIT_DISTFILES_CDROM=	"no license"
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Convert

CONFIGURE_STYLE=	perl

.include <bsd.port.mk>
