# $OpenBSD: Makefile,v 1.7.2.1 2000/09/15 05:01:42 marc Exp $

DISTNAME=	movemail-1.0
CATEGORIES=	mail
MASTER_SITES=	http://people.freebsd.org/~wosch/src/

MAINTAINER=	angelos@openbsd.org

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

FAKE_FLAGS=PREFIX=${PREFIX}
.include <bsd.port.mk>
