# $OpenBSD: Makefile,v 1.2.8.1 2000/09/15 04:47:28 marc Exp $
#

    SUBDIR += base64
    SUBDIR += btoa
    SUBDIR += ish
    SUBDIR += mimepp
    SUBDIR += mpack
    SUBDIR += p5-DateManip
    SUBDIR += p5-Convert-UU
    SUBDIR += p5-MIME-Base64
    SUBDIR += recode
    SUBDIR += rpm2cpio
    SUBDIR += trans
#   SUBDIR += uudeview
#   SUBDIR += uudx
#   SUBDIR += uulib
#   SUBDIR += xdeview

.include <bsd.port.subdir.mk>
