# $OpenBSD: Makefile,v 1.1.1.1.2.1 2001/05/07 23:35:33 miod Exp $

COMMENT=		'change terminal modes, and perform non-blocking reads'

DISTNAME=		TermReadKey-2.14
PKGNAME=		p5-Term-ReadKey-2.14
CATEGORIES=		devel perl5
NEED_VERSION=		1.406

MAINTAINER=		Peter Stromberg <wilfried@openbsd.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Term

CONFIGURE_STYLE=	perl

.include <bsd.port.mk>
