#!/bin/sh
#
# ADMfzap wrapper.
#
# Dug Song <dugsong@monkey.org>
#
# $Id$

LIBFZAP=y0y0y0

function usage {
    echo "Usage: ADMfzap [-p port] command ..." >&2; exit 1
}

while getopts p: opt 2>&-; do
    case "$opt" in
	p) LPORT=$OPTARG ;;
	\?) usage ;;
    esac
done

shift $(($OPTIND - 1))

if [ $# -eq 0 ]; then usage; fi

LD_PRELOAD=$LIBFZAP exec $*

