# $OpenBSD: Makefile,v 1.9.2.1 2000/09/15 05:39:01 marc Exp $

DISTNAME=	xonix-1.4
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/

MAINTAINER=	ports@openbsd.org

LICENSE_TYPE=		BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

USE_IMAKE=      	Yes
FAKE=			Yes

.include <bsd.port.mk>
