# $OpenBSD: Makefile,v 1.10.2.1 2000/09/15 04:43:00 marc Exp $

DISTNAME=	tosha-0.6
CATEGORIES=	audio
NEED_VERSION=	1.311
MASTER_SITES=	ftp://ftp.tu-clausthal.de/pub/unix/audio/

MAINTAINER=	angelos@openbsd.org

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
