#!/bin/sh
#
# $OpenBSD: php3-enable,v 1.1.2.1 2000/09/15 05:22:12 marc Exp $

MODULE=y0y0y0/lib/libphp3.so
INI=y0y0y0/share/doc/php3/php3.ini-dist

if [ ! -f ${MODULE} ]; then
    echo "can't find php3 module (${MODULE})"
    exit 1
else
    echo "enabling php3 module..."
    /usr/sbin/apxs -i -a -n php3 ${MODULE}
    echo "note: a sample php3.ini file can be found as ${INI} and should be"
    echo "      installed into /var/www/conf."
fi
