# $OpenBSD: Makefile,v 1.7.2.1 2000/12/18 18:57:41 brad Exp $

ONLY_FOR_ARCHS=	i386
NEED_VERSION=	1.322

PROGRAM_V=	4.75
V2:=		${PROGRAM_V:S/.//}

DISTNAME=	communicator-v${V2}-us.x86-bsdi-bsd2
PKGNAME=	communicator-${PROGRAM_V}p1
LOCATION=	bsdi21/complete_install
DIRNAME=	communicator-v${V2}.x86-bsdi-bsd2

NO_BUILD=	Yes

.include <bsd.port.mk>
