# $OpenBSD: Makefile,v 1.7.2.1 2000/09/15 04:50:46 marc Exp $

DISTNAME=       xcopilot-0.6.6
CATEGORIES=     emulators pilot
FAKE=		Yes

MAINTAINER=     angelos@openbsd.org

LICENSE_TYPE=		GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=   http://xcopilot.cuspy.com/build/

USE_X11=	Yes

GNU_CONFIGURE=	Yes

.include <bsd.port.mk>
