# $OpenBSD: Makefile,v 1.5.2.2 2010/07/27 02:29:36 william Exp $

COMMENT =	file cck field

DISTNAME = 	filefield-6.x-3.5
PKGNAME =	drupal6-filefield-3.5

RUN_DEPENDS =	::www/drupal6/cck

.include <bsd.port.mk>
