# $OpenBSD: Makefile,v 1.5.2.1 2010/05/25 03:26:58 william Exp $

COMMENT =	file cck field

DISTNAME = 	filefield-6.x-3.3
PKGNAME =	drupal6-filefield-3.3

RUN_DEPENDS =	::www/drupal6/cck

.include <bsd.port.mk>
