# $OpenBSD: Makefile,v 1.30.2.2 2007/06/17 13:45:20 sturm Exp $

COMMENT=	"tty-based e-mail client"

VERSION=	1.4.2.3
DISTNAME=	mutt-${VERSION}
MASTER_SITES=	${MASTER_SITES_MUTT}

.include <bsd.port.mk>
