# $OpenBSD: Makefile,v 1.30.4.1 2007/05/05 08:46:48 sturm Exp $

COMMENT=	"tty-based e-mail client"

VERSION=	1.4.2.2
DISTNAME=	mutt-${VERSION}i
PKGNAME=	${DISTNAME}p0
MASTER_SITES=	${MASTER_SITES_MUTT}

.include <bsd.port.mk>
