# New ports collection makefile for:	xd
# Date created:		10 Nov 1999
# Whom:			Kevin Lo <kevlo@openbsd.org>
#
# $OpenBSD: Makefile,v 1.3.2.1 2000/09/15 05:05:46 marc Exp $
#

DISTNAME=	xd-8087
CATEGORIES=	misc
MASTER_SITES=	http://www.vector.co.jp/authors/VA004959/xd/
 
MAINTAINER=	kevlo@openbsd.org

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

FAKE_FLAGS=PREFIX=${PREFIX}
.include <bsd.port.mk>
