# $OpenBSD: Makefile,v 1.8.2.1 2000/09/15 05:25:16 marc Exp $

DISTNAME=	lupe007
PKGNAME=	lupe-0.07
CATEGORIES=	x11
NEED_VERSION=	1.191
MASTER_SITES=	ftp://ftp.eos.hokudai.ac.jp/pub/X11/contrib/misc/

MAINTAINER=	ports@openbsd.org

LICENSE_TYPE=		PD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

USE_IMAKE=	Yes
XMKMF=		xmkmf
FAKE=		Yes

WRKDIST=	${WRKDIR}/lupe

.include <bsd.port.mk>
