# $OpenBSD: Makefile,v 1.7.2.1 2000/09/15 04:41:19 marc Exp $

DISTNAME=	xearth-1.1
CATEGORIES=	astro x11
MASTER_SITES=	ftp://cag.lcs.mit.edu/pub/tuna/

NO_CDROM=	"NOFEE:	Cannot sell"

LICENSE_TYPE=   NOFEE
PERMIT_PACKAGE_CDROM=   "Cannot sell."
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= "Cannot sell."
PERMIT_DISTFILES_FTP=   Yes

MAINTAINER=	pjanzen@openbsd.org

USE_IMAKE=	Yes
FAKE=		Yes

.include <bsd.port.mk>
