# $OpenBSD: Makefile,v 1.7.4.1 2000/09/15 04:40:26 marc Exp $
# $FreeBSD: Makefile,v 1.19 1997/11/20 08:21:26 tg Exp $
#

     SUBDIR += arc
     SUBDIR += bzip
     SUBDIR += bzip2
     SUBDIR += fastjar
     SUBDIR += freeze
     SUBDIR += gshar+gunshar
     SUBDIR += gtar
     SUBDIR += ha
#    SUBDIR += hpack.non-usa.only
     SUBDIR += lha
     SUBDIR += lzo
     SUBDIR += lzop
     SUBDIR += nulib
     SUBDIR += p5-Compress-LZO
     SUBDIR += p5-Compress-Zlib
     SUBDIR += rar
     SUBDIR += unace
     SUBDIR += unarj
     SUBDIR += unrar
     SUBDIR += unzip
#    SUBDIR += unzip.with_encryption
     SUBDIR += zip
#    SUBDIR += zip.with_encryption
     SUBDIR += zoo

.include <bsd.port.subdir.mk>
