# $OpenBSD: Makefile,v 1.9.2.1 2000/09/15 04:47:46 marc Exp $
# $FreeBSD: Makefile,v 1.24 1997/10/04 23:32:05 andreas Exp $
#
     SUBDIR += db
     SUBDIR += gdbm
#    SUBDIR += gnats
#    SUBDIR += msql
     SUBDIR += mysql
     SUBDIR += mysql:pth
     SUBDIR += p5-AsciiDB-TagFile
     SUBDIR += p5-DBD-Pg
#    SUBDIR += p5-DBD-mysql
     SUBDIR += p5-DBI
#    SUBDIR += p5-Msql
#    SUBDIR += p5-Mysql
#    SUBDIR += p5-Pg
     SUBDIR += postgresql
     SUBDIR += postgresql,docs
     SUBDIR += postgresql,tcl
     SUBDIR += postgresql,tcl,docs
#    SUBDIR += typhoon
#    SUBDIR += xmbase-grok
     SUBDIR += xmysql
     SUBDIR += xmysqladmin

.include <bsd.port.subdir.mk>
