# $OpenBSD: Makefile,v 1.16.2.2 2001/11/15 07:33:48 jakob Exp $

DISTNAME=	postfix-20010228-pl07
PKGNAME=	postfix-20010228.pl07

MAINTAINER=	Jakob Schlyter <jakob@openbsd.org>

MASTER_SITE_SUBDIR=	official

.include <bsd.port.mk>
