# $OpenBSD: Makefile,v 1.16.2.1 2001/11/13 19:36:57 jakob Exp $

DISTNAME=	postfix-20010228-pl06
PKGNAME=	postfix-20010228.pl06

MAINTAINER=	Jakob Schlyter <jakob@openbsd.org>

MASTER_SITE_SUBDIR=	official

.include <bsd.port.mk>
