# $OpenBSD: Makefile,v 1.30.2.1 2002/06/04 10:36:18 jakob Exp $

VERSION=	1.1.11

DISTNAME=	postfix-${VERSION}
PKGNAME=	postfix-${VERSION}

MAINTAINER=	Jakob Schlyter <jakob@openbsd.org>

MASTER_SITE_SUBDIR=	official

TLSVERSION=	0.8.11a
TLSDISTNAME=	pfixtls-${TLSVERSION}-${VERSION}-0.9.6d

.include <bsd.port.mk>
