# $OpenBSD: Makefile,v 1.4.2.1 2010/07/23 00:41:38 william Exp $

COMMENT =	test site as another user
CATEGORIES =	devel

DISTNAME =	masquerade-6.x-1.4
PKGNAME =	drupal6-masquerade-1.4


.include <bsd.port.mk>
