# OpenBSD makefile for:	xautolock
# Version required:	pl-11
# Date created:		16 March 1998	
# Whom:			Thomas Graichen
#
# $OpenBSD: Makefile,v 1.5.2.1 2000/09/15 05:25:41 marc Exp $
#

NEED_VERSION=	1.293
DISTNAME=	xautolock-pl11
CATEGORIES=	x11
COMES_WITH=	2.3
COMMENT=-fire up programs in case of user inactivity under X
MIRROR_DISTFILE=no

MASTER_SITES=	ftp://ftp.science.unitn.it/pub/unix/X11/utilities/

MAINTAINER=	graichen@OpenBSD.ORG

.include <bsd.port.mk>
