# $OpenBSD: Makefile,v 1.7.2.1 2000/09/15 05:05:23 marc Exp $
# $FreeBSD: Makefile,v 1.1.1.1 1999/03/05 17:07:28 nectar Exp $

DISTNAME=	delay-1.4
CATEGORIES=	misc
NEED_VERSION=	1.310
MASTER_SITES=	http://rei.onegeek.org/~tom/software/delay/dl/

HOMEPAGE=	http://rei.onegeek.org/~tom/software/delay/

MAINTAINER=	brad@openbsd.org

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

SEPARATE_BUILD=	concurrent
CONFIGURE_STYLE= gnu

.include <bsd.port.mk>
