#!/bin/sh
# $OpenBSD: DEINSTALL,v 1.2.2.1 2000/09/15 05:10:37 marc Exp $
#
# vtun de-installation

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_FILE=/etc/vtund.conf

if [ -f $CONFIG_FILE ]; then
    echo
    echo "+---------------"
    echo "| To completely deinstall the $1 package you need to perform"
    echo "| this step as root:"
    echo "|"
    echo "|           rm -f $CONFIG_FILE"
    echo "|           rm -rf /var/log/vtund"
    echo "|"
    echo "| Do not do this if you plan on re-installing $1"
    echo "| at some future time."
    echo "+---------------"
    echo
fi

exit 0
