# $OpenBSD: Makefile,v 1.4.8.1 2007/08/01 06:11:44 ajacoutot Exp $

COMMENT=		extracts files from Microsoft CAB archives

DISTNAME=		cabextract-1.2
CATEGORIES=		archivers

HOMEPAGE=		http://www.kyz.uklinux.net/cabextract.php3

MAINTAINER=		Steve Shockley <steve.shockley@shockley.net>

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
WANTLIB=		c

MASTER_SITES=		http://www.kyz.uklinux.net/downloads/

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
