# $OpenBSD: Makefile,v 1.7.2.1 2002/12/26 22:28:19 pvalchev Exp $

COMMENT= 		"X11 toolkit, utilities"
CATEGORIES=		x11 x11/kde
VERSION=		3.0.5a
DISTNAME=		kdeutils-${VERSION}

LIB_DEPENDS= kdecore.4,DCOP,kabc,kdefakes,kdefx,kdeprint,kdesu,kdeui,kio,kparts,kspell,vcard::x11/kde/libs3
RUN_DEPENDS= ::comms/efax

.include <bsd.port.mk>
