#!/bin/sh
#
# $Id: pre-configure,v 1.1 1995/02/24 15:18:24 ats Exp $
#

cp ${CURDIR}/files/cdrom_freebsd.c ${WRKSRC}
cp ${CURDIR}/files/cdrom_freebsd.h ${WRKSRC}
cp ${WRKSRC}/xcdplayer.1 ${WRKSRC}/xcdplayer.man
