# $OpenBSD: Makefile,v 1.5.2.1 2002/09/13 06:11:58 pvalchev Exp $

COMMENT=	"breakout game for X Window"

DISTNAME=	xbreaky-0.0.4
PKGNAME=	${DISTNAME}p1
CATEGORIES=	games
NEED_VERSION=	1.515
MASTER_SITES=	${HOMEPAGE}

HOMEPAGE=	http://xbreaky.sourceforge.net/

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
