#!/bin/sh -
#
#	pre-configure script for Elm port to FreeBSD 2.0
#	$Id: pre-configure,v 1.16 1996/12/23 06:08:21 ache Exp $

PortsDir=$PORTSDIR
  CurDir=$CURDIR
  WrkSrc=$WRKSRC

if [ ${OPSYS} == "OpenBSD" ]; then
	/bin/sh ${FILESDIR}/config.sh.OpenBSD
else
	/bin/sh ${FILESDIR}/config.sh.FreeBSD
fi
