# $OpenBSD: Makefile,v 1.40.4.1 2007/05/05 08:46:48 sturm Exp $

COMMENT=	"tty-based e-mail client, development version"

VERSION=	1.5.12
DISTNAME=	mutt-${VERSION}
PKGNAME=	${DISTNAME}p0
MASTER_SITES=	${MASTER_SITES_MUTT:=devel/}

FLAVORS=	hcache idn sidebar

.include <bsd.port.mk>
