# $OpenBSD: Makefile,v 1.37.2.1 2006/06/24 17:16:11 sturm Exp $

COMMENT=	"tty-based e-mail client, development version"

VERSION=	1.5.11
DISTNAME=	mutt-${VERSION}
PKGNAME=	${DISTNAME}p3
MASTER_SITES=	${MASTER_SITES_MUTT:=devel/}

AUTOCONF_VERSION= 2.59

FLAVORS=	hcache idn sidebar

.include <bsd.port.mk>
