# $OpenBSD: Makefile,v 1.13.6.1 2003/07/21 01:20:03 brad Exp $

COMMENT=	"3D block-dropping game"

DISTNAME=	xbl-1.1.1
CATEGORIES=	games
HOMEPAGE=	http://www710.univ-lyon1.fr/ftp/xbl/xbl.html

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	ftp://ftp710.univ-lyon1.fr/pub/xbl/

USE_X11=	Yes
CONFIGURE_STYLE=gnu	# also uses imake

NO_REGRESS=	Yes

.include <bsd.port.mk>
