# $OpenBSD: Makefile,v 1.7.2.1 2000/09/15 05:38:24 marc Exp $
#

DISTNAME=	xev111
PKGNAME=        xbat-1.11
CATEGORIES=     games
NEED_VERSION=	1.191

MAINTAINER=	ports@openbsd.org

PERMIT_PACKAGE_CDROM=	"possible copyright infringement"
PERMIT_PACKAGE_FTP=	"possible copyright infringement"
PERMIT_DISTFILES_CDROM=	"possible copyright infringement"
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=   http://www.nemoto.ecei.tohoku.ac.jp/~wai/Xbat/

USE_IMAKE=	Yes
WRKDIST=	${WRKDIR}/Xev111
ALL_TARGET=	xbat

.include <bsd.port.mk>
