# $OpenBSD: Makefile,v 1.6.2.1 2000/09/15 05:18:25 marc Exp $

DISTNAME=	usbutil-0.4
CATEGORIES=	sysutils
NEED_VERSION=	1.302

MASTER_SITES=	ftp://ftp.augustsson.net/pub/netbsd/

MAINTAINER=	jakob@openbsd.org

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
