# $OpenBSD: Makefile,v 1.3.2.1 2010/05/25 03:25:10 william Exp $

COMMENT =	image cck field

DISTNAME = 	imagefield-6.x-3.3
PKGNAME =	drupal6-imagefield-3.3

RUN_DEPENDS =	::www/drupal6/filefield

.include <bsd.port.mk>
