# $OpenBSD: Makefile,v 1.7.2.1 2000/09/15 05:09:13 marc Exp $

DISTNAME=	httptunnel-3.0.3
CATEGORIES=	net
NEED_VERSION=	1.310
MASTER_SITES=	http://www.nocrew.org/software/httptunnel/ \
		ftp://ftp.nocrew.org/pub/nocrew/unix/

HOMEPAGE=	http://www.nocrew.org/software/httptunnel/

MAINTAINER=	jakob@openbsd.org

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

SEPARATE_BUILD=	concurrent
CONFIGURE_STYLE= gnu

.include <bsd.port.mk>
