# $OpenBSD: Makefile,v 1.6.2.1 2000/09/15 04:53:05 marc Exp $

DISTNAME=	compface
PKGNAME=	compface-1.0
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.xemacs.org/pub/xemacs/aux/

PERMIT_PACKAGE_CDROM=	"no fee"
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	"no fee"
PERMIT_DISTFILES_FTP=	Yes

MAINTAINER=	hgweigand@wiesbaden.netsurf.de

.include <bsd.port.mk>
