# $OpenBSD: Makefile,v 1.9.2.1 2000/09/15 05:09:52 marc Exp $

DISTNAME=	ngrep-1.38
CATEGORIES=     net
NEED_VERSION=	1.310
MASTER_SITES=	http://www.packetfactory.net/Projects/ngrep/

HOMEPAGE=	http://www.packetfactory.net/Projects/ngrep/

MAINTAINER=	dugsong@monkey.org

PERMIT_PACKAGE_CDROM=	"no obvious license"
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	"no obvious license"
PERMIT_DISTFILES_FTP=	Yes

USE_GMAKE=  yes
CONFIGURE_STYLE= gnu dest

WRKDIST=	${WRKDIR}/ngrep

ALL_TARGET=	ngrep

.include <bsd.port.mk>
