# $OpenBSD: Makefile,v 1.9.2.1 2002/12/26 22:28:18 pvalchev Exp $

COMMENT=		games for KDE

CATEGORIES=		x11 x11/kde games
VERSION=		3.0.5a
DISTNAME=		kdegames-${VERSION}

LIB_DEPENDS= kdecore.4,DCOP,kdefx,kdeprint,kdesu,kdeui,kio,kparts::x11/kde/libs3
SEPARATE_BUILD=simple

.include <bsd.port.mk>
