# OpenBSD makefile for:	xtimer
# Version required:	0.8087
# Date created:		May 20 1998
# Whom:			Angelos D. Keromytis
#
# $OpenBSD: Makefile,v 1.6.2.1 2000/09/15 05:05:51 marc Exp $
#

DISTNAME=	xtimer-8089
PKGNAME=	xtimer-0.8089
CATEGORIES=	misc
MASTER_SITES=	http://hp.vector.co.jp/authors/VA004959/xtimer/

MAINTAINER=	ports@openbsd.org

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	imake

.include <bsd.port.mk>
