# OpenBSD makefile for:	dclock
# Version required:	1.0
# Date created:		8 January 1998
# Whom:			Don Schmidt
#
# $OpenBSD: Makefile,v 1.5.2.1 2000/09/15 05:24:42 marc Exp $

DISTNAME=	bclock-1.0
CATEGORIES=	x11
NEED_VERSION=	1.310
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=     X11/clocks

MAINTAINER=	ports@OpenBSD.ORG

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	imake

.include <bsd.port.mk>
