# $Id: Makefile,v 1.1.1.1 2007/09/13 21:44:27 sthen Exp $

COMMENT=	collection of utilities for C programmers

DISTNAME=	cutils-1.6
PKGNAME=	${DISTNAME}p0
CATEGORIES=	devel

HOMEPAGE=	http://www.sigala.it/sandro/software.php

MAINTAINER=	Paul Irofti <bulibuta@sdf.lonestar.org>

# BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB= 		c

MASTER_SITES=		http://www.sigala.it/sandro/files/

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
