# $OpenBSD: Makefile,v 1.8.2.2 2011/01/21 08:59:42 jasper Exp $

SHARED_ONLY=	Yes

COMMENT=	interface to the uulib library

DISTNAME=	Convert-UUlib-1.34
EPOCH=		0
CATEGORIES=	converters
MODULES=	cpan

MAINTAINER=	Ibrahim Khalifa <ibo@toontown.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
