# $OpenBSD: Makefile,v 1.2.4.1 2005/04/27 14:58:32 robert Exp $

NOT_FOR_ARCHS=	${NO_SHARED_ARCHS}

COMMENT=	"interface to the uulib library"

DISTNAME=	Convert-UUlib-1.051
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	converters perl5

MAINTAINER=	Ibrahim Khalifa <ibo@toontown.org>

# Artistic & GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=Convert/}

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
