# $OpenBSD: Makefile,v 1.7.2.1 2000/09/15 04:50:43 marc Exp $

    SUBDIR += bochs
    SUBDIR += bochs:debugger
    SUBDIR += frodo
    SUBDIR += freebsd_lib
    SUBDIR += linux_lib
    SUBDIR += simh
    SUBDIR += wine
    SUBDIR += x48
    SUBDIR += xcopilot

.include <bsd.port.subdir.mk>
