# $OpenBSD: Makefile,v 1.7.6.1 2003/08/13 01:26:23 brad Exp $

COMMENT=	"tool for capturing data from TCP connections"

DISTNAME=	tcpflow-0.21
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.circlemud.org/pub/jelson/tcpflow/

HOMEPAGE=       http://www.circlemud.org/~jelson/software/tcpflow/

MAINTAINER=	Dan Weeks <danimal@danimal.org>

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=        gnu

.include <bsd.port.mk>
