# $OpenBSD: Makefile,v 1.13.2.1 2000/09/15 04:42:28 marc Exp $

DISTNAME=	bladeenc-0.93.7-src-unstable-2
PKGNAME=	bladeenc-0.93.7
CATEGORIES=	audio
NEED_VERSION=	1.310
MASTER_SITES=	http://bladeenc.mp3.no/source/ \
		http://www.physik.TU-Berlin.DE/~ibex/ports/distfiles/

HOMEPAGE=	http://bladeenc.mp3.no/

MAINTAINER=	brad@openbsd.org

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	gnu

WRKDIST=	${WRKDIR}/${PKGNAME}

.include <bsd.port.mk>
