# OpenBSD makefile for:			p5-Mail-POP3Client
# Version required:			1.15
# Date created:				May 16 1998
# Whom:	      				Angelos D. Keromytis
#
#   $OpenBSD: Makefile,v 1.5.2.1 2000/09/15 05:01:48 marc Exp $
#

DISTNAME=	POP3Client-2.3
PKGNAME=	p5-Mail-POP3Client-2.3
CATEGORIES=	mail perl5
NEED_VERSION=	1.308
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Mail

MAINTAINER=	angelos@openbsd.org

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
CONFIGURE_STYLE=	perl

.include <bsd.port.mk>
