#!/bin/sh
# $OpenBSD: DEINSTALL,v 1.1.1.1.4.1 2000/09/15 04:53:07 marc Exp $
#
# fnlib de-installation

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_FILE=/etc/fnrc

if [ -f ${CONFIG_FILE} ]; then
    echo
    echo "+---------------"
    echo "| To completely deinstall the $1 package you need to perform"
    echo "| this step as root:"
    echo "|"
    echo "|           rm -f ${CONFIG_FILE}"
    echo "|"
    echo "| Do not do this if you plan on re-installing $1"
    echo "| at some future time."
    echo "+---------------"
    echo
fi

exit 0
