# $OpenBSD: Makefile,v 1.5.2.1 2000/09/15 05:38:52 marc Exp $

DISTNAME=	xmahjongg-3.3
CATEGORIES=	games x11
NEED_VERSION=	1.308
MASTER_SITES=	http://www.lcdf.org/~eddietwo/xmahjongg/

MAINTAINER=	fgsch@openbsd.org

PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
