# $OpenBSD: Makefile,v 1.13.2.1 2000/09/15 05:18:19 marc Exp $
# Original from: Ejovi Nuwere <ejovi@ejovi.net>

DISTNAME=	setquota-0.1
CATEGORIES=	sysutils
NEED_VERSION=	1.191
MASTER_SITES=	ftp://ftp.jurai.net/users/winter/

MAINTAINER= 	ports@OpenBSD.ORG

LICENSE_TYPE=		BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WRKDIST=	${WRKDIR}/setquota/
FAKE_FLAGS=	PREFIX=${PREFIX}

.include <bsd.port.mk>
