# $OpenBSD: Makefile,v 1.5.2.1 2002/12/26 22:28:18 pvalchev Exp $

COMMENT= 		"some useless kde applications"
CATEGORIES=		x11 x11/kde games
VERSION=		3.0.5a
DISTNAME=		kdetoys-${VERSION}
LIB_DEPENDS= kdecore.4,DCOP,kdefx,kdeprint,kdesu,kdeui,khtml,kio,kjava,kparts,kscreensaver::x11/kde/libs3

.include <bsd.port.mk>
