# $OpenBSD: Makefile,v 1.5.2.1 2000/09/15 05:13:42 marc Exp $
#

     SUBDIR += cyrproxy
     SUBDIR += d1489
     SUBDIR += wget-msgs
     SUBDIR += xcyrillic
     SUBDIR += xruskb
     SUBDIR += xruskb:motif

.include <bsd.port.subdir.mk>
