# $OpenBSD: Makefile,v 1.6.4.1 2000/09/15 05:12:13 marc Exp $
# $FreeBSD: Makefile,v 1.4 1997/11/17 11:55:01 tg Exp $
#

     SUBDIR += 9menu
#    SUBDIR += 9term
     SUBDIR += 9wm
#    SUBDIR += Xg
     SUBDIR += larswm
     SUBDIR += rc
     SUBDIR += rc,readline
     SUBDIR += rc,editline
     SUBDIR += sam
     SUBDIR += tcs
     SUBDIR += wily

.include <bsd.port.subdir.mk>
