# $OpenBSD: Makefile,v 1.2.2.1 2000/09/15 05:21:52 marc Exp $

CATEGORIES=		www
NEED_VERSION=		1.317

HOMEPAGE=	http://artax.karlin.mff.cuni.cz/%7Emikulas/links/
MAINTAINER=	espie@cvs.openbsd.org

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

DISTNAME=	links-0.92

MASTER_SITES=	http://artax.karlin.mff.cuni.cz/%7Emikulas/links/download/
CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
