# $OpenBSD: Makefile,v 1.10.2.1 2000/09/15 05:01:23 marc Exp $
#

DISTNAME=	exmh-1.6.9
CATEGORIES=	mail tk80
NEED_VERSION=	1.293
IGNORE=		"has been superseded by exmh2"
MIRROR_DISTFILE=no
NO_CHECKSUM=	Yes
DISTFILES=


MAINTAINER=	ports@openbsd.org

LICENSE_TYPE=		NONE
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
COMMENT=-superseded by exmh2

.include <bsd.port.mk>
