# $OpenBSD: Makefile,v 1.1.1.1.2.1 2001/05/07 23:36:38 miod Exp $

COMMENT=		'GNU Readline Library Wrapper Module'

DISTNAME=		Term-ReadLine-Gnu-1.09
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5
NEED_VERSION=		1.406

MAINTAINER=		Peter Stromberg <wilfried@openbsd.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Term

CONFIGURE_STYLE=	perl

.include <bsd.port.mk>
