# $OpenBSD: Makefile,v 1.10.2.1 2000/09/15 05:05:14 marc Exp $

DISTNAME=	buffer-1.17.1
CATEGORIES=	misc
NEED_VERSION=	1.234
MASTER_SITES=	http://people.freebsd.org/~steve/distfiles/

MAINTAINER=	naddy@openbsd.org

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

USE_BZIP2=	Yes

WRKDIST=	${WRKDIR}

.include <bsd.port.mk>
