# $OpenBSD: Makefile,v 1.4.2.1 2010/10/26 07:02:10 stephan Exp $

COMMENT =	printer-friendly pages in drupal

DISTNAME = 	print-6.x-1.11
PKGNAME =	drupal6-printer-friendly-1.11

.include <bsd.port.mk>
