# $OpenBSD: Makefile,v 1.4.2.1 2000/09/15 05:03:04 marc Exp $
#

DISTNAME=	xspread2.1
PKGNAME=	xspread-2.1
CATEGORIES=	math

MAINTAINER=	ports@openbsd.org

LICENSE_TYPE=		GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	ftp://sunsite.unc.edu/pub/Linux/distributions/slackware/source/xap/xspread/
# ${MASTER_SITE_SUNSITE} isn't appropriate because distributions/ isn't
# mirrored.

USE_IMAKE=	Yes
FAKE=		Yes

.include <bsd.port.mk>
