# $OpenBSD: Makefile,v 1.2.2.1 2010/10/25 11:09:09 stephan Exp $

COMMENT =	create sensible urls automatically

DISTNAME = 	pathauto-6.x-1.5
PKGNAME =	drupal6-pathauto-1.5
RUN_DEPENDS =	::www/drupal6/token

.include <bsd.port.mk>
