# Makefile for:		parse
# Version required:	1.0
# Date created:		27 Jan 2000
# Whom:			dugsong@monkey.org
#
# $OpenBSD: Makefile,v 1.3.2.1 2000/09/15 05:15:23 marc Exp $

PKGNAME=	parse-1.0

CATEGORIES=	security

MAINTAINER=	dugsong@monkey.org

PERMIT_PACKAGE_CDROM=   "commercial.  licensing restrictions."
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= "commercial.  licensing restrictions."
PERMIT_DISTFILES_FTP=   Yes       

NO_CDROM=	"not for resale"

MASTER_SITES=	ftp://ftp.sdsc.edu/pub/security/PICS/parse/

DISTNAME=	parse

EXTRACT_SUFX=	.t.gz

.include <bsd.port.mk>
